language: java

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk11
  
branches:
  only:
    - master

cache:
  directories:
    - .autoconf
    - $HOME/.m2

script: "mvn package -Dmaven.javadoc.skip=true -B -V"
